version: '3.3'
services:
  upload-microservice:
    container_name: upload-microservice
    hostname: upload-microservice
    build: .
    depends_on:
      - upload-redis
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
  upload-redis:
    image: redis:4.0
    container_name: upload-redis
    hostname: upload-redis
    ports:
      - '6379:6379'