version: '3.3'
services:
  app:
    container_name: dev-upload-microservice
    hostname: dev-upload-microservice
    build: .
    depends_on:
      - redis
    environment:
      - NODE_ENV=dev
    ports:
      - '3000:3000'
  redis:
    image: redis:4.0
    container_name: dev-upload-redis
    hostname: dev-upload-redis
    ports:
      - '6379:6379'