version: '3.3'
services:
  development-upload-microservice:
    container_name: development-upload-microservice
    hostname: development-upload-microservice
    build: .
    depends_on:
      - development-redis
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
  development-redis:
    image: redis:4.0
    container_name: development-upload-redis
    hostname: development-upload-redis
    ports:
      - '6379:6379'